[package]
name = "verify-skip-kun"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
poise = "0.6.1"
serenity = "0.12.2"
tokio = { version = "1.38.0", features = [
  "macros",
  "rt-multi-thread",
  "signal",
] }
